### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by elisonkaloshi** [heltonWernik/OpenLuck#5]
I think a search option would be helpful

**Comment by rishabhyadavm07** [comment]
Hello elisonkaloshi, 

I think it is not a efficient and good choice to put the search option as we can easily search through the output using grep.

`./OpenFuck | grep 0x6a`

The above command easily gives the desired output.

Thank you

**Comment by heltonWernik** [comment]
As Rishab comment says there is no need for this feature. I will close the issue.
